const TEMP_MAIL_DOMAINS = [
  'tempmail.com',
  'throwaway.email',
  'guerrillamail.com',
  'guerrillamail.info',
  'guerrillamail.net',
  'guerrillamail.org',
  'sharklasers.com',
  'grr.la',
  'guerrillamailblock.com',
  'pokemail.net',
  'spam4.me',
  'mailinator.com',
  'temp-mail.org',
  '10minutemail.com',
  '10minutemail.net',
  'fakeinbox.com',
  'tempail.com',
  'tempr.email',
  'discard.email',
  'throwawaymail.com',
  'yopmail.com',
  'yopmail.fr',
  'mailnesia.com',
  'maildrop.cc',
  'getnada.com',
  'mohmal.com',
  'tempmailo.com',
  'trashmail.com',
  'trashmail.de',
  'trashmail.net',
  'trashmail.org',
  'mintemail.com',
  'mytrashmail.com',
  'filzmail.com',
  'getairmail.com',
  'mailcatch.com',
  'mail-temp.com',
  'mailtemp.info',
  'tempmailaddress.com',
  'tmpmail.org',
  'tmpmail.net',
  'tempm.com',
  'mt2014.com',
  'mt2015.com',
  'emailondeck.com',
  'tempsky.com',
  'gmailnator.com',
  'emailfake.com',
  'fakemailgenerator.com',
  'mailpoof.com',
  'spamgourmet.com',
  'jetable.org',
  'mailexpire.com',
  'meltmail.com',
  'sofortmail.de',
  'spamfree24.org',
  'spamhole.com',
  'incognitomail.org',
  'mailnull.com',
  'mailscrap.com',
  'mailzilla.com',
  'mailzilla.org',
];

export function isTempMail(email: string): boolean {
  const domain = email.split('@')[1]?.toLowerCase();
  if (!domain) return true;
  return TEMP_MAIL_DOMAINS.some(tempDomain => 
    domain === tempDomain || domain.endsWith('.' + tempDomain)
  );
}
